const paymentTypes=['CASH','G-CASH','MAYA','CREDIT','DEBIT','CHEQUE','SALMON','OTHER'];
const currency=new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'});
const today=new Date().toISOString().slice(0,10);
const seed=[
 {branch:'Parkmall',date:today,cash:65430,gcash:45210.75,maya:18750,credit:22300,debit:15120,cheque:8650,salmon:5260,other:4700,customers:957,actual:185420.75,reading:185420.75,status:'Matched'},
 {branch:'Mactan',date:today,cash:54310,gcash:33150,maya:12750,credit:17600,debit:10905.2,cheque:6800,salmon:4200,other:2600,customers:742,actual:142315.2,reading:142315.2,status:'Matched'},
 {branch:'Tabunok',date:today,cash:42150,gcash:22100,maya:8950,credit:11200,debit:7600,cheque:3500,salmon:2165.5,other:1100,customers:512,actual:98260.5,reading:98260.5,status:'With Difference'}
];
let reports=JSON.parse(localStorage.getItem('ksc_reports')||'null')||seed;
const byId=id=>document.getElementById(id);
const value=id=>Number(byId(id).value||0);
const fieldKey=t=>t.toLowerCase().replace('-','');
function showToast(message){const t=byId('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function format(n){return currency.format(Number(n)||0)}
function buildFields(){byId('paymentFields').innerHTML=paymentTypes.map(t=>`<label>${t}<input class="payment" id="p_${fieldKey(t)}" type="number" min="0" step="0.01" value="0" required></label>`).join('');document.querySelectorAll('.payment').forEach(i=>i.addEventListener('input',updateEntryTotals))}
function paymentTotal(){return paymentTypes.reduce((s,t)=>s+value('p_'+fieldKey(t)),0)}
function updateEntryTotals(){const total=paymentTotal();byId('reportedTotal').textContent=format(total);byId('checkerReported').textContent=format(total);updateDifference()}
function updateDifference(){const d=value('actualReceived')-paymentTotal();byId('difference').textContent=format(d);byId('difference').style.color=d===0?'#138a45':'#b42318';byId('checkerStatus').textContent=d===0&&value('actualReceived')>0?'Matched':value('actualReceived')===0?'Pending':'With Difference';byId('checkerStatus').className='badge '+(d===0&&value('actualReceived')>0?'matched':value('actualReceived')===0?'pending':'different')}
function persist(){localStorage.setItem('ksc_reports',JSON.stringify(reports))}
function currentPayload(status='Submitted'){const item={branch:byId('branch').value,date:byId('businessDate').value,customers:value('customers'),actual:0,reading:0,status,storeRemarks:byId('storeRemarks').value};paymentTypes.forEach(t=>item[fieldKey(t)]=value('p_'+fieldKey(t)));return item}
function reportTotal(r){return paymentTypes.reduce((s,t)=>s+Number(r[fieldKey(t)]||0),0)}
function upsert(report){const i=reports.findIndex(r=>r.branch===report.branch&&r.date===report.date);if(i>=0)reports[i]={...reports[i],...report};else reports.unshift(report);persist();render()}
function render(){const date=byId('filterDate').value||today;const list=reports.filter(r=>r.date===date);const rep=list.reduce((s,r)=>s+reportTotal(r),0),act=list.reduce((s,r)=>s+Number(r.actual||0),0),cust=list.reduce((s,r)=>s+Number(r.customers||0),0);byId('metricReported').textContent=format(rep);byId('metricActual').textContent=format(act);byId('metricDifference').textContent=format(act-rep);byId('metricCustomers').textContent=cust.toLocaleString();byId('reportRows').innerHTML=list.map(r=>{const d=Number(r.actual||0)-reportTotal(r);const status=r.status||'Pending';const cls=status==='Matched'?'matched':status==='With Difference'?'different':'pending';return `<tr><td>${r.branch}</td><td>${r.date}</td><td>${format(reportTotal(r))}</td><td>${format(r.actual)}</td><td style="color:${d===0?'#138a45':'#b42318'}">${format(d)}</td><td>${r.customers}</td><td><span class="badge ${cls}">${status}</span></td></tr>`}).join('')||'<tr><td colspan="7">No submissions for this date.</td></tr>';renderSummary(list[0])}
function renderSummary(r){if(!r){byId('executiveSummary').innerHTML='<p>No branch report selected.</p>';return}const rows=paymentTypes.map(t=>`<div class="summary-row"><span>${t}</span><strong>${format(r[fieldKey(t)])}</strong></div>`).join('');const d=Number(r.actual||0)-reportTotal(r);byId('executiveSummary').innerHTML=`<div class="summary-title">${r.branch} · ${r.date}</div>${rows}<div class="summary-row"><span>IN TOTAL</span><strong>${format(reportTotal(r))}</strong></div><div class="summary-row"><span>Reading</span><strong>${format(r.reading)}</strong></div><div class="summary-row"><span>Difference</span><strong>${format(d)}</strong></div><div class="summary-row"><span>Customers</span><strong>${Number(r.customers).toLocaleString()}</strong></div>`}
function loadSelected(){const r=reports.find(x=>x.branch===byId('branch').value&&x.date===byId('businessDate').value);paymentTypes.forEach(t=>byId('p_'+fieldKey(t)).value=r?.[fieldKey(t)]||0);byId('customers').value=r?.customers||0;byId('storeRemarks').value=r?.storeRemarks||'';byId('actualReceived').value=r?.actual||0;byId('reading').value=r?.reading||0;byId('receivedBy').value=r?.receivedBy||'';byId('checkerRemarks').value=r?.checkerRemarks||'';byId('entryStatus').textContent=r?.status||'Draft';updateEntryTotals()}
function exportCsv(){const head=['Branch','Date',...paymentTypes,'Reported Total','Actual Received','Reading','Difference','Customers','Status'];const rows=reports.map(r=>[r.branch,r.date,...paymentTypes.map(t=>r[fieldKey(t)]||0),reportTotal(r),r.actual||0,r.reading||0,(r.actual||0)-reportTotal(r),r.customers||0,r.status||'Pending']);const csv=[head,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`KakingStoreCash-${today}.csv`;a.click();URL.revokeObjectURL(a.href)}
buildFields();byId('businessDate').value=today;byId('filterDate').value=today;byId('todayLabel').textContent=new Date().toLocaleDateString('en-PH',{weekday:'long',year:'numeric',month:'long',day:'numeric'});byId('entryForm').addEventListener('submit',e=>{e.preventDefault();upsert(currentPayload('Pending Verification'));byId('entryStatus').textContent='Submitted';showToast('Daily report submitted successfully.')});byId('saveDraftBtn').addEventListener('click',()=>{upsert(currentPayload('Draft'));showToast('Draft saved on this device.')});byId('verifyBtn').addEventListener('click',()=>{const reported=paymentTotal(),actual=value('actualReceived'),diff=actual-reported,remarks=byId('checkerRemarks').value.trim();if(!byId('receivedBy').value.trim())return showToast('Enter the checker name.');if(diff!==0&&!remarks)return showToast('Remarks are required for a difference.');const base=currentPayload(diff===0?'Matched':'With Difference');upsert({...base,actual,reading:value('reading'),receivedBy:byId('receivedBy').value.trim(),checkerRemarks:remarks,verifiedAt:new Date().toISOString()});showToast('Deposit verification saved.')});['actualReceived','reading'].forEach(id=>byId(id).addEventListener('input',updateDifference));['branch','businessDate'].forEach(id=>byId(id).addEventListener('change',loadSelected));byId('filterDate').addEventListener('change',render);byId('exportBtn').addEventListener('click',exportCsv);document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`[data-view="${b.dataset.view}"]`);byId('pageTitle').textContent=b.textContent==='Dashboard'?'Daily Operations Dashboard':b.textContent;document.querySelector(b.dataset.view==='checker'?'.checker-card':b.dataset.view==='reports'?'.table-card':b.dataset.view==='summary'?'.summary-card':'.entry-card').scrollIntoView({behavior:'smooth',block:'start'})}));loadSelected();render();